# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25939b4fc4c640001e61982e3314499855d77394e4ef921bd4be791d96e12fd29ab5fbb1d860e7eae4ad186f61ffb76f7c711760f2f5ee13fb572c8c395798c8

test:
  secret_key_base: f6e758ce32fcd6fc5344044cdb9b49bf4187820953c355e12fc8d225ffe9049b197e279caacb14adbe914645b0417ae779fefdf197cea941b3e62022119af49b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
